// svelte-src/lib/components/GiphyPicker.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Drawer } from 'vaul-svelte';
  import { apiGet } from '../utils/api';
  
  export let onClose: () => void;
  export let onSelect: (url: string) => void;
  
  let query = '';
  let gifs: any[] = [];
  let isLoading = false;
  let searchTimeout: ReturnType<typeof setTimeout> | null = null;

  async function loadGifs(overrideQuery?: string) {
    isLoading = true;
    try {
      const q = overrideQuery !== undefined ? overrideQuery : query;
      console.log('[GiphyPicker] Loading GIFs for query:', q);
      const res = await apiGet(`/api/giphy?q=${encodeURIComponent(q)}&limit=24`);
      console.log('[GiphyPicker] API response status:', res.status);
      if (res.ok) {
        const data = await res.json();
        gifs = data.gifs || [];
        console.log('[GiphyPicker] Loaded', gifs.length, 'GIFs');
      } else {
        console.error('[GiphyPicker] API error:', res.status, res.statusText);
      }
    } catch (error) {
      console.error('[GiphyPicker] Failed to load GIFs:', error);
    } finally {
      isLoading = false;
    }
  }

  onMount(() => {
    loadGifs(); // Loads trending by default
  });

  function handleInput() {
    console.log('[GiphyPicker] Input changed, query:', query);
    if (searchTimeout) clearTimeout(searchTimeout);
    searchTimeout = setTimeout(() => {
      console.log('[GiphyPicker] Searching for:', query);
      loadGifs();
    }, 400); // 400ms debounce
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      e.preventDefault();
      if (searchTimeout) clearTimeout(searchTimeout);
      console.log('[GiphyPicker] Enter pressed, searching for:', query);
      loadGifs();
    }
  }
</script>

<!-- Unified Drawer for Mobile and Desktop -->
<Drawer.Root open={true} onOpenChange={(open) => { if (!open) onClose(); }}>
  <Drawer.Portal>
    <Drawer.Overlay class="fixed inset-0 bg-black/80 z-[200]" />
    <Drawer.Content class="fixed bottom-0 left-0 right-0 md:top-1/2 md:left-1/2 md:-translate-x-1/2 md:-translate-y-1/2 md:bottom-auto md:right-auto z-[200] flex flex-col bg-black rounded-t-[20px] md:rounded-2xl max-h-[92vh] md:max-h-[85vh] md:w-full md:max-w-md outline-none" style="padding-bottom: env(safe-area-inset-bottom);">
      <div class="mx-auto w-12 h-1.5 flex-shrink-0 rounded-full bg-white/10 my-3 md:hidden"></div>
      
      <!-- Header/Search -->
      <div class="px-4 py-3 border-b border-white/10 shrink-0 flex items-center gap-3 md:px-6 md:py-4">
        <div class="flex-1 relative">
          <svg class="absolute left-3 top-1/2 -translate-y-1/2 text-white/40 w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
          </svg>
          <input
            type="text"
            bind:value={query}
            on:input={handleInput}
            on:keydown={handleKeyDown}
            placeholder="Search GIPHY..."
            class="w-full bg-white/5 border border-white/10 rounded-xl py-2.5 pl-9 pr-4 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-white/30 transition-colors"
            autofocus
          />
        </div>
        <button
          type="button"
          on:click={onClose}
          class="p-2 -mr-2 text-white/40 hover:text-white transition-all duration-200 hover:scale-110 active:scale-95"
          aria-label="Close"
        >
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>

      <!-- GIF Grid -->
      <div class="flex-1 overflow-y-auto p-4 scrollbar-hide md:p-6">
        {#if isLoading && gifs.length === 0}
          <div class="text-center py-12 text-white/30 text-sm animate-pulse-subtle">Searching...</div>
        {:else if gifs.length === 0}
          <div class="text-center py-12 text-white/30 text-sm animate-fade-in">No GIFs found</div>
        {:else}
          <div class="grid grid-cols-2 gap-2 stagger-fade-in">
            {#each gifs as gif}
              <button
                type="button"
                on:click={() => onSelect(gif.url)}
                class="relative rounded-lg overflow-hidden bg-white/5 aspect-square hover:opacity-80 transition-all duration-200 touch-manipulation focus:outline-none focus:ring-2 focus:ring-white/50 hover:scale-105 active:scale-95"
              >
                <img
                  src={gif.preview}
                  alt={gif.title || 'GIF'}
                  class="absolute inset-0 w-full h-full object-cover"
                  loading="lazy"
                />
              </button>
            {/each}
          </div>
        {/if}
      </div>
    </Drawer.Content>
  </Drawer.Portal>
</Drawer.Root>

// src/components/GiphyPicker.tsx
"use client";

import { useEffect, useRef, useState, useCallback } from "react";

interface GiphyPickerProps {
  onSelect: (gifUrl: string, gifId: string) => void;
  onClose: () => void;
}

interface GiphyGif {
  id: string;
  images: {
    fixed_height_small: { url: string; width: string; height: string };
    original: { url: string };
  };
  title: string;
}

export default function GiphyPicker({ onSelect, onClose }: GiphyPickerProps) {
  const [query, setQuery] = useState("");
  const [gifs, setGifs] = useState<GiphyGif[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const search = useCallback(async (q: string) => {
    setLoading(true);
    setError("");
    try {
      const endpoint = q.trim()
        ? `/api/giphy/search?q=${encodeURIComponent(q.trim())}`
        : `/api/giphy/search?trending=1`;
      const res = await fetch(endpoint);
      if (!res.ok) throw new Error("Failed to load GIFs");
      const data = await res.json();
      setGifs(data.data ?? []);
    } catch {
      setError("Could not load GIFs");
      setGifs([]);
    } finally {
      setLoading(false);
    }
  }, []);

  // Load trending on mount
  useEffect(() => {
    search("");
    setTimeout(() => inputRef.current?.focus(), 100);
  }, [search]);

  // Debounced search
  useEffect(() => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => search(query), 400);
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [query, search]);

  // Close on Escape
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onClose]);

  return (
    <div className="absolute bottom-full left-0 right-0 z-50 mx-2 mb-2 max-h-80 overflow-hidden rounded-lg border border-[#1e1f22] bg-[#2b2d31] shadow-xl md:left-auto md:right-4 md:mx-0 md:w-96">
      {/* Header */}
      <div className="flex items-center gap-2 border-b border-[#1e1f22] px-3 py-2">
        <input
          ref={inputRef}
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search GIFs..."
          className="min-w-0 flex-1 rounded-md bg-[#1e1f22] px-3 py-1.5 text-sm text-gray-200 placeholder-gray-500 outline-none"
        />
        <button
          onClick={onClose}
          className="flex h-7 w-7 items-center justify-center rounded text-gray-400 hover:text-white"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      {/* Content */}
      <div className="scroll-area grid max-h-60 grid-cols-2 gap-1 overflow-y-auto p-2">
        {loading && gifs.length === 0 && (
          <div className="col-span-2 flex items-center justify-center py-8">
            <div className="h-5 w-5 animate-spin rounded-full border-2 border-gray-600 border-t-[#5865f2]" />
          </div>
        )}
        {error && (
          <p className="col-span-2 py-4 text-center text-xs text-red-400">{error}</p>
        )}
        {gifs.map((gif) => (
          <button
            key={gif.id}
            onClick={() => onSelect(gif.images.fixed_height_small.url, gif.id)}
            className="overflow-hidden rounded transition-transform hover:scale-105"
            title={gif.title}
          >
            <img
              src={gif.images.fixed_height_small.url}
              alt={gif.title}
              className="h-24 w-full object-cover"
              loading="lazy"
            />
          </button>
        ))}
        {!loading && !error && gifs.length === 0 && (
          <p className="col-span-2 py-4 text-center text-xs text-gray-500">No GIFs found</p>
        )}
      </div>

      {/* Giphy attribution */}
      <div className="border-t border-[#1e1f22] px-3 py-1 text-right">
        <span className="text-[10px] text-gray-600">Powered by GIPHY</span>
      </div>
    </div>
  );
}
